[project]
name = "magic-antidote"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=4.0.0",
    "modal>=1.1.3",
    "torch>=2.8.0",
    "transformers>=4.55.4",
]
